package com.moyz.adi.common.enums;

import lombok.Getter;

@Getter
public enum ErrorEnum {
    SUCCESS("00000", "SUCCESS"),
    A_URL_NOT_FOUND("A0001", "A_URL_NOT_FOUND"),
    A_PARAMS_ERROR("A0002", "A_PARAMS_ERROR"),
    A_REQUEST_TOO_MUCH("A0003", "A_REQUEST_TOO_MUCH"),
    A_LOGIN_ERROR("A0004", "A_LOGIN_ERROR"),
    A_LOGIN_ERROR_MAX("A0005", "A_LOGIN_ERROR_MAX"),
    A_LOGIN_CAPTCHA_ERROR("A0006", "A_LOGIN_CAPTCHA_ERROR"),
    A_USER_NOT_EXIST("A0007", "A_USER_NOT_EXIST"),
    A_CONVERSATION_NOT_EXIST("A0008", "A_CONVERSATION_NOT_EXIST"),
    A_IMAGE_NUMBER_ERROR("A0009", "A_IMAGE_NUMBER_ERROR"),
    A_IMAGE_SIZE_ERROR("A0010", "A_IMAGE_SIZE_ERROR"),
    A_FILE_NOT_EXIST("A0011", "A_FILE_NOT_FOUND"),
    A_DRAWING("A0012", "A_DRAWING"),
    A_USER_EXIST("A0013", "A_USER_EXIST"),
    A_FIND_PASSWORD_CODE_ERROR("A0014", "A_FIND_PASSWORD_CODE_ERROR"),
    A_USER_WAIT_CONFIRM("A0015", "A_USER_WAIT_CONFIRM"),
    A_USER_NOT_AUTH("A0016", "A_USER_NOT_AUTH"),
    A_DATA_NOT_FOUND("A0017", "A_DATA_NOT_FOUND"),
    A_UPLOAD_FAIL("A0018", "A_UPLOAD_FAIL"),
    A_UPLOAD_FILE_TYPE_NOT_ALLOWED("A0058", "A_UPLOAD_FILE_TYPE_NOT_ALLOWED"),
    A_UPLOAD_IMAGE_TYPE_NOT_ALLOWED("A0059", "A_UPLOAD_IMAGE_TYPE_NOT_ALLOWED"),
    A_QA_ASK_LIMIT("A0019", "A_QA_ASK_LIMIT"),
    A_QA_ITEM_LIMIT("A0020", "A_QA_ITEM_LIMIT"),
    A_CONVERSATION_EXIST("A0021", "A_CONVERSATION_EXIST"),
    A_MODEL_NOT_FOUND("A0022", "A_MODEL_NOT_FOUND"),
    A_MODEL_ALREADY_EXIST("A0023", "A_MODEL_ALREADY_EXIST"),
    A_CONVERSATION_NOT_FOUND("A0024", "A_CONVERSATION_NOT_FOUND"),
    A_AI_IMAGE_NOT_FOUND("A0024", "A_AI_IMAGE_NOT_FOUND"),
    A_ENABLE_MODEL_NOT_FOUND("A0025", "A_ENABLE_MODEL_NOT_FOUND"),
    A_DOC_INDEX_DOING("A0026", "A_DOC_INDEX_DOING"),
    A_PRESET_CONVERSATION_NOT_EXIST("A0027", "A_PRESET_CONVERSATION_NOT_EXIST"),
    A_CONVERSATION_TITLE_EXIST("A0028", "A_CONVERSATION_TITLE_EXIST"),
    A_AI_IMAGE_NO_AUTH("A0029", "A_AI_IMAGE_NO_AUTH"),
    A_USER_NOT_FOUND("A0030", "A_USER_NOT_FOUND"),
    A_ACTIVE_CODE_INVALID("A0031", "A_ACTIVE_CODE_INVALID"),
    A_OLD_PASSWORD_INVALID("A0032", "A_OLD_PASSWORD_INVALID"),
    A_OPT_TOO_FREQUENTLY("A0032", "A_OPT_TOO_FREQUENTLY"),
    A_DRAW_NOT_FOUND("A00033", "A_DRAW_NOT_FOUND"),
    A_WF_NOT_FOUND("A00034", "A_WF_NOT_FOUND"),
    A_WF_DISABLED("A0035", "A_WF_DISABLED"),
    A_WF_NODE_NOT_FOUND("A0036", "A_WF_NODE_NOT_FOUND"),
    A_WF_NODE_CONFIG_NOT_FOUND("A0037", "A_WF_NODE_CONFIG_NOT_FOUND"),
    A_WF_NODE_CONFIG_ERROR("A0038", "A_WF_NODE_CONFIG_ERROR"),
    A_WF_INPUT_INVALID("A0039", "A_WF_INPUT_INVALID"),
    A_WF_INPUT_MISSING("A0040", "A_WF_INPUT_MISSING"),
    A_WF_MULTIPLE_START_NODE("A0041", "A_WF_MULTIPLE_START_NODE"),
    A_WF_START_NODE_NOT_FOUND("A0042", "A_WF_START_NODE_NOT_FOUND"),
    A_WF_END_NODE_NOT_FOUND("A0043", "A_WF_END_NODE_NOT_FOUND"),
    A_WF_EDGE_NOT_FOUND("A0044", "A_WF_EDGE_NOT_FOUND"),
    A_WF_RUNTIME_NOT_FOUND("A00045", "A_WF_RUNTIME_NOT_FOUND"),
    A_SEARCH_QUERY_IS_EMPTY("A00046", "A_SEARCH_QUERY_IS_EMPTY"),
    A_WF_COMPONENT_NOT_FOUND("A00047", "A_WF_COMPONENT_NOT_FOUND"),
    A_WF_RESUME_FAIL("A00048", "A_WF_RESUME_FAIL"),
    A_MAIL_SENDER_EMPTY("A00049", "A_MAIL_SENDER_EMPTY"),
    A_MAIL_SENDER_CONFIG_ERROR("A00050", "A_MAIL_SENDER_CONFIG_ERROR"),
    A_MAIL_RECEIVER_EMPTY("A00051", "A_MAIL_RECEIVER_EMPTY"),
    A_MCP_SERVER_NOT_FOUND("A00052", "A_MCP_SERVER_NOT_FOUND"),
    A_USER_MCP_SERVER_NOT_FOUND("A00053", "A_USER_MCP_SERVER_NOT_FOUND"),
    A_PARAMS_INVALID_BY_("A00054", "A_PARAMS_INVALID_BY_"),
    A_AI_MESSAGE_NOT_FOUND("A00055", "A_AI_MESSAGE_NOT_FOUND"),
    A_USER_QUESTION_NOT_FOUND("A00056", "A_USER_QUESTION_NOT_FOUND"),
    A_PLATFORM_NOT_MATCH("A0057", "A_PLATFORM_NOT_MATCH"),
    B_UNCAUGHT_ERROR("B0001", "B_UNCAUGHT_ERROR"),
    B_COMMON_ERROR("B0002", "B_COMMON_ERROR"),
    B_GLOBAL_ERROR("B0003", "B_GLOBAL_ERROR"),
    B_SAVE_IMAGE_ERROR("B0004", "B_SAVE_IMAGE_ERROR"),
    B_FIND_IMAGE_404("B0005", "B_FIND_IMAGE_404"),
    B_DAILY_QUOTA_USED("B0006", "B_DAILY_QUOTA_USED"),
    B_MONTHLY_QUOTA_USED("B0007", "B_MONTHLY_QUOTA_USED"),
    B_LLM_NOT_SUPPORT("B0008", "B_LLM_NOT_SUPPORT"),
    B_LLM_SECRET_KEY_NOT_SET("B0009", "B_LLM_SECRET_KEY_NOT_SET"),
    B_MESSAGE_NOT_FOUND("B0008", "B_MESSAGE_NOT_FOUND"),
    B_LLM_SERVICE_DISABLED("B0009", "B_LLM_SERVICE_DISABLED"),
    B_KNOWLEDGE_BASE_IS_EMPTY("B0010", "B_KNOWLEDGE_BASE_IS_EMPTY"),
    B_NO_ANSWER("B0011", "B_NO_ANSWER"),
    B_SAVE_FILE_ERROR("B0012", "B_SAVE_FILE_ERROR"),
    B_BREAK_SEARCH("B0013", "B_BREAK_SEARCH"),
    B_GRAPH_FILTER_NOT_FOUND("B0014", "B_GRAPH_FILTER_NOT_FOUND"),
    B_DB_ERROR("B0015", "B_DB_ERROR"),
    B_ACTIVE_USER_ERROR("B0016", "B_ACTIVE_USER_ERROR"),
    B_RESET_PASSWORD_ERROR("B0017", "B_RESET_PASSWORD_ERROR"),
    B_IMAGE_LOAD_ERROR("B0018", "B_IMAGE_LOAD_ERROR"),
    B_IO_EXCEPTION("B0019", "B_IO_EXCEPTION"),
    B_SERVER_EXCEPTION("B0020", "B_SERVER_EXCEPTION"),
    B_DELETE_FILE_ERROR("B0021", "B_DELETE_FILE_ERROR"),
    B_WF_RUN_ERROR("B0022", "B_WF_RUN_ERROR"),
    B_WF_NODE_DEFINITION_NOT_FOUND("B0023", "B_WF_NODE_DEFINITION_NOT_FOUND"),
    B_DIR_CREATE_FAIL("B0024", "B_DIR_CREATE_FAIL"),
    B_LLM_TEMPERATURE_ERROR("B0025", "B_LLM_TEMPERATURE_ERROR"),
    B_ASR_SETTING_NOT_FOUND("B0026", "B_ASR_SETTING_NOT_FOUND"),
    B_URL_INVALID("B0027", "B_URL_INVALID"),
    B_ASR_MODEL_NOT_FOUND("B0028", "B_ASR_MODEL_NOT_FOUND"),
    B_TTS_SETTING_NOT_FOUND("B0029", "B_TTS_SETTING_NOT_FOUND"),
    B_TTS_MODEL_NOT_FOUND("B0030", "B_TTS_MODEL_NOT_FOUND"),
    B_VOICE_NOT_FOUND("B0031", "B_VOICE_NOT_FOUND"),
    B_NOT_SUPPORT_FUNCTION("B0032", "B_NOT_SUPPORT_FUNCTION"),
    C_DRAW_FAIL("C0001", "C_DRAW_FAIL"),
    C_ALI_OSS_CONFIG_ERROR("C0002", "C_ALI_OSS_CONFIG_ERROR"),
    C_LLM_RESPONSE_INVALID("C0003", "C_LLM_RESPONSE_INVALID"),
    C_WF_COMPONENT_DELETED_FAIL_BY_USED("C0004", "C_WF_COMPONENT_DELETED_FAIL_BY_USED"),
    C_TTS_FAIL("C0005", "C_TTS_FAIL");

    private final String code;
    private final String info;

    ErrorEnum(String code, String info) {
        this.code = code;
        this.info = info;
    }

    public static ErrorEnum getErrorEnum(String code) {
        ErrorEnum result = null;
        for (ErrorEnum c : ErrorEnum.values()) {
            if (c.getCode().equals(code)) {
                result = c;
                break;
            }
        }
        if (null == result) {
            result = B_COMMON_ERROR;
        }
        return result;
    }

}
