server {
    listen 80;
    server_name localhost;
    charset utf-8;
    proxy_buffering off;
    error_page 500 502 503 504 /50x.html;

    # Backend API
    location /api/ {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://aideepin-api:9999/;
    }

    # Admin Web
    location /admin/ {
        proxy_pass http://aideepin-admin-web:80/;
    }

    # User Web
    location / {
        proxy_pass http://aideepin-user-web:80;
    }

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}
