version: '3'

services:
  aideepin-admin-web:
    container_name: aideepin-admin-web
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
