package com.moyz.adi.common.entity;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableName;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
@TableName("adi_ai_image")
@Schema(title = "ai images", description = "Image generated by ai")
public class AiImage extends BaseEntity {

    @TableField("user_id")
    private Long userId;

    @TableField("uuid")
    private String uuid;

    @TableField("ai_model_name")
    private String AiModelName;

    @TableField("prompt")
    private String prompt;

    @TableField("generate_size")
    private String generateSize;

    @TableField("generate_quality")
    private String generateQuality;

    @TableField("generate_number")
    private Integer generateNumber;

    @Schema(title = "file uuid")
    @TableField("original_image")
    private String originalImage;

    @Schema(title = "file uuid")
    @TableField("mask_image")
    private String maskImage;

    @TableField("resp_images_path")
    private String respImagesPath;

    @Schema(title = "generated image uuids")
    @TableField("generated_images")
    private String generatedImages;

    @TableField("interacting_method")
    private Integer interactingMethod;

    @TableField("process_status")
    private Integer processStatus;
}
